export default {
	SET_BOARDS_SUCCESS: 'SET_BOARDS_SUCCESS',

	CREATE_BOARD_REQUEST: 'CREATE_BOARD_REQUEST',
	CREATE_BOARD_SUCCESS: 'CREATE_BOARD_SUCCESS',

	SET_CURRENT_BOARD_SUCCESS: 'SET_CURRENT_BOARD_SUCCESS'
};