export default {
	GET_BOARDS_REQUEST: 'GET_BOARDS_REQUEST',
	GET_BOARDS_SUCCESS: 'GET_BOARDS_SUCCESS',

	CREATE_BOARD_REQUEST: 'CREATE_BOARD_REQUEST',
	CREATE_BOARD_SUCCESS: 'CREATE_BOARD_SUCCESS',
};