export default {
	SET_CARDS_SUCCESS: 'SET_CARDS_SUCCESS',

	CREATE_CARD_REQUEST: 'CREATE_CARD_REQUEST',
	CREATE_CARD_SUCCESS: 'CREATE_CARD_SUCCESS',

	SET_CURRENT_CARD_SUCCESS: 'SET_CURRENT_CARD_SUCCESS',
	SET_CURRENT_CARD_LOADING: 'SET_CURRENT_CARD_LOADING',

	SET_CURRENT_CARDS_SUCCESS: 'SET_CURRENT_CARDS_SUCCESS',
	SET_CURRENT_CARDS_LOADING: 'SET_CURRENT_CARDS_LOADING'
};