export default {
	SET_LISTS_SUCCESS: 'SET_LISTS_SUCCESS',

	CREATE_LIST_REQUEST: 'CREATE_LIST_REQUEST',
	CREATE_LIST_SUCCESS: 'CREATE_LIST_SUCCESS',

	SET_CURRENT_LISTS_SUCCESS: 'SET_CURRENT_LISTS_SUCCESS',
	SET_CURRENT_LISTS_LOADING: 'SET_CURRENT_LISTS_LOADING'
};