export default {
	GET_USERS_REQUEST: 'GET_USERS_REQUEST',
	GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',

	GET_USERS_FAILURE: 'GET_USERS_FAILURE',
	SAVE_USERS_REQUEST: 'SAVE_USERS_REQUEST',

	SAVE_USERS_SUCCESS: 'SAVE_USERS_SUCCESS',
	SAVE_USERS_FAILURE: 'SAVE_USERS_FAILURE',
	
	LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
	LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
};