export default {
	LOGIN_USERS_REQUEST: 'LOGIN_USERS_REQUEST',
	LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
	LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',

	SET_USER_SUCCESS: 'SET_USER_SUCCESS',
	SET_USER_LOADING: 'SET_USER_LOADING',
	SET_USER_FAIL: 'SET_USER_FAIL'
};