export default {
	GET_USERS_REQUEST: 'GET_USERS_REQUEST',
	GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',

	GET_USERS_FAILURE: 'GET_USERS_FAILURE',
	SAVE_USERS_REQUEST: 'SAVE_USERS_REQUEST',

	SAVE_USERS_SUCCESS: 'SAVE_USERS_SUCCESS',
	SAVE_USERS_FAILURE: 'SAVE_USERS_FAILURE',
	
	LOGIN_USERS_FAILURE: 'LOGIN_USERS_FAILURE',
	LOGIN_USERS_SUCCESS: 'LOGIN_USERS_SUCCESS',
};